version: '3'
services:
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: 'fileSystem'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    tty: true
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
  api:
    depends_on:
      - 'db'
    command: sh -c 'npm run dev'
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - PORT=5000
      - SECRET_KEY=secret
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=fileSystem
      - EMAIL_KEY=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
      - MAINLGUN_KEY=e7223fb3cc28899d39194a761e4d18e3-7fba8a4e-3c7e837d
      - MAINLGUN_DOMAIN=sandbox5e00a505791f4af39ec383b8b62b5d54.mailgun.org
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
